name: Process and Publish Video
on:
  repository_dispatch:
    types: [video_uret]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLIENT_SECRETS_BASE64: ${{ secrets.CLIENT_SECRETS_BASE64 }}
      TOKEN_PICKLE_BASE64: ${{ secrets.TOKEN_PICKLE_BASE64 }}
      
    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Create Secrets
        run: |
          echo "$CLIENT_SECRETS_BASE64" | base64 -d > client_secrets.json
          echo "$TOKEN_PICKLE_BASE64" | base64 -d > token.pickle

      - name: Process and Upload
        env:
          PATH_CAT: ${{ github.event.client_payload.category }}
        run: |
          mkdir -p output
          # Bıçağın donuk kaldığı kısımları kırpan, hareketli döngü sağlayan komut
          ffmpeg -y -i "content/shorts/$PATH_CAT/current_video.mp4" -vf "split[a][b];[b]reverse[b_rev];[a]trim=start=0:end=0.5[a_start];[b_rev]trim=start=0:end=0.5[b_rev_start];[a_start][b_rev_start]xfade=transition=fade:duration=0.5:offset=0" -c:v libx264 -crf 23 output/final_video.mp4
          python upload_to_youtube.py --file "output/final_video.mp4" --category "$PATH_CAT"
